services: 
  terraria-server:
    image: diyagi/terraria-server-docker:latest
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - ./worlds:/home/terraria/worlds
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 7777
      VERSION: "latest"
      WORLD: "My Little Test World"
      AUTOCREATE: 2
      DIFFICULTY: 2
      MAXPLAYERS: 4
      PASSWORD: ""
      MOTD: "BEAR!"
      SECURE: 0
      NPCSTREAM: 0      
